# Generated by Django 3.0 on 2021-08-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_preguntasrespondidas_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
